### PR TITLE
Don't show deprecation warnings in production env

### PR DESCRIPTION
**Pull request by deepsweet**

### CODE REVIEW

**Comment by deepsweet** [comment]
```
10 01 2018 13:16:11.359:ERROR [launcher]: Cannot start ChromeHeadless
[0110/131611.142547:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/google/chrome/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by xaviervia** [comment]
Yeah I have no idea what that error is

**Comment by xaviervia** [comment]
F**k it, it's passing locally. Merge and release

**Comment by deepsweet** [comment]
`(╯°□°）╯︵ ┻━┻`

**Pull request merged**
